name = "proxyrouter"
main = "worker.js"
compatibility_date = "2024-03-21"

[observability]
enabled = false

[vars]
# 模型配置
LITE_MODEL = "gemini-3.1-flash-lite-preview"
SIMPLE_MODEL = "gemini-3-flash-preview"
COMPLEX_MODEL = "gemini-3.1-pro-preview"

[placement]
region = "aws:us-east-1"
